# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
rouge: true
future: true

# Title
name: Civic Tech Book Club
subtitle: 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: ''

# Author/Organization info to be displayed in the templates

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: " "
  internal: true
- text: Discussions
  url: discussions
  internal: true
- text: Reading List
  url: readinglist
  internal: true   

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Book Club
  description: Code for this website
  url: https://github.com/rebeccawilliams/bookclub

group:
- name: Civic Tech Book Club
  description: Google Group Listserv
  url: https://groups.google.com/forum/#!forum/civictechbookclub

# Style Variables
brand_color: "#eca702"
